server:
  port: 8095
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/adityarastogi1212/microservices
          clone-on-start: true
